setup.py: Fix invalid python_requires
Fix python_requires to use >=3.5 instead of >=3.5.*, as the latter
is invalid.  It caused distlib to crash:

```
$ python -c "import distlib.database; list(distlib.database.DistributionPath(include_egg=True).get_distributions())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/distlib/database.py", line 213, in get_distributions
    self._generate_cache()
  File "/usr/lib/python3.8/site-packages/distlib/database.py", line 167, in _generate_cache
    for dist in self._yield_distributions():
  File "/usr/lib/python3.8/site-packages/distlib/database.py", line 157, in _yield_distributions
    yield old_dist_class(r.path, self)
  File "/usr/lib/python3.8/site-packages/distlib/database.py", line 879, in __init__
    metadata = self._get_metadata(path)
  File "/usr/lib/python3.8/site-packages/distlib/database.py", line 965, in _get_metadata
    metadata.add_requirements(requires)
  File "/usr/lib/python3.8/site-packages/distlib/metadata.py", line 1039, in add_requirements
    self._legacy.add_requirements(requirements)
  File "/usr/lib/python3.8/site-packages/distlib/metadata.py", line 575, in add_requirements
    self['Requires-Dist'] += requirements
  File "/usr/lib/python3.8/site-packages/distlib/metadata.py", line 276, in __setitem__
    return self.set(name, value)
  File "/usr/lib/python3.8/site-packages/distlib/metadata.py", line 453, in set
    if not scheme.is_valid_matcher(v.split(';')[0]):
  File "/usr/lib/python3.8/site-packages/distlib/version.py", line 703, in is_valid_matcher
    self.matcher(s)
  File "/usr/lib/python3.8/site-packages/distlib/version.py", line 115, in __init__
    raise ValueError('\'.*\' not allowed for '
ValueError: '.*' not allowed for '>=' constraints
```